config/routes.rb
Rails.application.routes.draw do
  get 'order/index'

  devise_for :users
  root 'welcome#index'

  resources :welcome do
    collection do
      get 'contact'
      get 'pictures'
      get 'price_list'
      get 'conditions'
      post 'send_mail'
    end
  end

  resources :users
  resources :orders
  resources :rooms
  resources :images

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
  end

  def conditions
  end

  def pictures
  	@images = Image.all
  end

  def price_list
    @order = Order.new
  end

  def send_mail
    UserMailer.email_from_contact(params[:email],params[:name],params[:phone],params[:text]).deliver_later
    flash[:success] = 'Email byl odeslán.'
    render :index
  end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_container_header.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Penzion whitezralok
            <small><%= nazev%></small>
        </h1>
        <ol class="breadcrumb">
            <li><%= link_to 'Penzion whitezralok', root_path %></li>
            <li class="active"><%= nazev %></li>
        </ol>
    </div>
</div>

app/views/welcome/conditions.html.erb
<%= render :partial => "welcome/container_header",:locals => {:nazev => 'Obchodní podmínky'} -%>
<div class="row">
  <div class='col-sm-11'>
      <div class="form-group">
          <blockquote  id = "licence_show">
              <h3>Všeobecné obchodní podmínky</h3>
              <h4>Všeobecné obchodní a storno podmínky - Penzion Whitezralok </h4>
              <p>Všeobecné obchodní a storno podmínky (dále jen podmínky) Penzionu Whitezralok (dále jen penzion) upravují vzájemný smluvní vztah mezi provozovatelem penzionu – Marian Jašek, Ztracená 322/1, 779 00 Olomouc, IČ 45228027 (dále jen provozovatelem) a klientem - fyzickou nebo právnickou osobou, která pobyt v penzionu jako objednatel objednává (dále jen klient).
              </p>
              <h4>I. Objednávka pobytu, vznik smluvního vztahu </h4>
              <p>Klient si objednává  služby v penzionu zadáním objednávky přes rezervační rozhraní na internetových stránkách penzionu. Podstatné náležitosti zakládající řádně vystavenou objednávku nebo požadavek na rezervaci jsou:  jméno a příjmení klienta, adresa trvalého bydliště, kontakt (telefon, e-mail), termín čerpání služeb. Předané osobní údaje klienta uvedené v objednávce nebo rezervaci pobytu použije penzion pouze pro uzavíraný smluvní vztah mezi penzionem a klientem. <br><br> Po řádně vystavené a podané objednávce je klient tímto dokumentem vázán. Potvrzením objednávky penzionem (dle čl. IV těchto podmínek) vzniká mezi klientem a penzionem smluvní vztah. Penzion se zavazuje zabezpečit klientovi služby v potvrzeném rozsahu a kvalitě a klient zaplatit penzionu smluvenou cenu. Podmínky smluvního vztahu platí pro všechny osoby uvedené v objednávce, kterou klient podal a penzion potvrdil.
              </p>
              <h4>II. Práva a povinnosti klienta</h4>
              <p>Klient má právo: <br> Být dostatečně a úplně informován penzionem o objednávaných službách, tj. jejich rozsahu, termínu a ceně, na řádné poskytnutí jím objednaných, penzionem potvrzených a zaplacených služeb,před zahájením pobytu zrušit potvrzenou objednávku za předpokladu dodržení stornovacích podmínek v souladu s čl. VII.,reklamovat vady poskytovaných služeb.<br><br> Klient je povinen: <br>Úplně a správně uvést všechny podstatné náležitosti objednávky, zaplatit penzionu v požadovaném termínu  plnou cenu za pobyt, respektovat předpisy zařízení, jejichž služby využívá, pečlivě si překontrolovat penzionem vystavené potvrzení pobytu (ubytovací voucher) a při zjištění jakékoliv nesrovnalosti kontaktovat neprodleně penzion.
              </p>
              <h4>III. Povinnosti penzionu ke klientovi </h4>
              <p>Penzion je povinen:<br>Poskytnout klientovi důležité informace k objednaným službám, potvrdit klientovi řádně objednané služby. Při závazné rezervaci nebo potvrzené objednávce zabezpečit klientovi služby v potvrzeném rozsahu a kvalitě. V případě odstoupení od potvrzené objednávky služeb ze strany klienta vyplatit nejpozději do 14 dnů po písemném obdržení storna zaplacenou částku na služby. Avšak pokud vznikne nárok penzionu na stornovací poplatky, vyplatí klientovi rozdíl mezi již zaplacenou zálohou a příslušnými stornovacími poplatky. </p>
              <h4>IV. Ceny služeb a jejich úhrada</h4>
              <p>Ceny služeb poskytovaných penzionem jsou uvedeny v objednávkovém systému a u jednotlivých pronajímaných apartmánů. Klient má nárok na slevu ve výši 10% z ceny ubytování při objednávce na 3-5 nocí, a ve výši 20% při objednávce na 6 a více nocí.Úhrada služeb je možná pouze na základě vystavené faktury penzionem. Tato faktura je klientovi doručena emailem nejpozději do 2 pracovních dní od vytvoření objednávky. Po zaplacení faktury je klientovi doručeno potvrzení služeb.
              </p>
              <h4>V. Potvrzení pobytu</h4>
              <p>K čerpání zaplacených služeb opravňuje klienta potvrzení vystavené emailem penzionem nejpozději do 2 dní od zaplacení. Klient je povinen překontrolovat správnost údajů na potvrzení uvedených. Při zjištění jakékoliv nesrovnalosti kontaktuje klient neprodleně penzion emailem whitezralok@atlas.cz nebo telefonicky na čísle 777 344 348.
              </p>
              <p>
                U právnických osob vystavíme fakturu na požádání po zaslání údajů (název firmy, IČ,DIČ).
              </p>
              <h4>VI. Nástup</h4>
              <p>Při nástupu se klient penzionu prokáže občanským průkazem, pasem nebo jiným průkazem totožnosti a potvrzením vystaveným penzionem. Po splnění uvedených formalit recepce klienta ubytuje a poskytne mu další informace k pobytu či k jiným objednaným službám. Nástup je možný v den nástupu po 14:00. Ukončení ubytování je poslední den pobyto nejpozději do 10:00. Klient je zavazuje předat apartmán ve stavu jak ho přejímal.
              </p>
              <h4>VII. Stornovací podmínky</h4>
              <p>Klient má právo kdykoliv pobyt zrušit, tj. odstoupit od potvrzené objednávky/rezervačního požadavku pobytu za níže uvedených podmínek. Toto odstoupení ze strany klienta (dále jen storno) musí být provedeno písemnou formou a prokazatelně doručeno penzionu. Storno podmínky se vztahují na zrušení rezervace ubytovacích, stravovacích a ostatních služeb ze strany objednavatele. Při zrušení rezervace od data, kdy rezervace byla hostem zadána do 120 hodin před předpokládaným začátkem čerpání služeb (tzn. nejpozději do 14:00 hodin 5 dní před datem příjezdu) si penzion neúčtuje storno poplatek. Při zrušení rezervace 48 až 120 hodin před předpokládaným začátkem čerpání služeb dle potvrzené objednávky (tzn. nejpozději do 14:00 hodin 2 den před datem příjezdu) je penzion oprávněn si účtovat storno poplatek ve výši 50% z objednaných služeb dle potvrzené objednávky. Při zrušení rezervace 48 hodin a méně před předpokládaným začátkem čerpání služeb dle potvrzené objednávky (tzn. mezi 14:00 hodin předvčerejšího dne až začátkem rezervovaných služeb) je penzion oprávněn účtovat storno poplatek ve výši 100 % z objednaných služeb dle potvrzené objednávky.
              </p>
              <h4>VIII. Závěrečná ustanovení</h4>
              <p>Tyto obchodní a storno podmínky jsou nedílnou součástí objednávky služeb. Celková ceny za poskytnuté služby bude uhrazena na základě vystaveného účetního dokladu (příjmový doklad, faktura), dle tam uvedených podmínek, který bude klientovi doručen do 2 pracovních dní od provedení závazné objednávky. Platbu lze provést převodem na základě údaju z potvrzovacího emailu. Platbu nelze provést platební kartou. Všeobecné obchodní a storno podmínky vstupují v platnost dne 1. 3. 2016. Změny a doplňky těchto podmínek mohou být individuálně mezi penzionem a klientem upraveny výlučně písemnou formou.
              </p><br><br>
          </blockquote>
      </div>
    </div>
</div>

app/views/welcome/contact.html.erb
        <!-- Page Heading/Breadcrumbs -->
        <%= render :partial => "welcome/container_header",:locals => {:nazev => 'Kontakty'} -%>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Map Column -->
            <div class="col-md-8">
                <!-- Embedded Google Map -->
                <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=49.9843953,17.313583617&amp;spn=49.9858764,17.2677366&amp;t=m&amp;z=15&amp;output=embed"></iframe>
            </div>
            <!-- Contact Details Column -->
            <div class="col-md-4">
                <h3>Kontaktní informace</h3>
                <p>
                    Dolní moravice<br> č.61<br>79501
                </p>
                <p><i class="fa fa-phone"></i>
                    <abbr title="Phone">Tel:</abbr>: +420 777 344 348</p>
                <p><i class="fa fa-envelope-o"></i>
                    <abbr title="Email">Email:</abbr>: <a href="mailto: whitezralok@atlas.cz">whitezralok@atlas.cz</a>
                </p>
            </div>
        </div>
        <!-- /.row -->

        <!-- Contact Form -->
        <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
        <div class="row">
            <div class="col-md-8">
                <h3>Pošlete nám zprávu</h3>
                <%= form_tag send_mail_welcome_index_path, method: :post do %>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Celé jméno</label>
                            <%= text_field_tag :name,nil, {class:'form-control', type: 'text', :required => true }%>
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Telefonní číslo</label>
                            <%= text_field_tag :phone,nil, {class:'form-control', type: 'tel', :required => true }%>
                        </div>
                    </div>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Vaše emailová adresa:</label>
                            <%= text_field_tag :email,nil, {class:'form-control', type: 'email', :required => true }%>
                        </div>
                    </div>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Zpráva:</label>
                            <%= text_area_tag :text, nil, {rows:"10",cols:"100", class:"form-control", :required => true, maxlength:"999", style:"resize:none"} %>
                        </div>
                    </div>
                    <div id="success"></div>
                    <!-- For success/fail messages -->
                    <button type="submit" class="btn btn-primary"> Odeslat zprávu </button>
                <% end %>
            </div>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Whitezralok 2016</p>
                </div>
            </div>
        </footer>

app/views/welcome/index.html.erb
<%= render :partial => "welcome/container_header",:locals => {:nazev => ''} -%>
<div class="row">
    <div class="col-md-6">
        <img class="img-responsive" src="/pictures/uvodni_fotka.jpg" alt="">
    </div>
    <div class="col-md-6">
        <h2>O penzionu</h2>
              <p>Penzion, skládající se ze čtyř apartmánů různých velikostí, se nachází v blízkosti obce Dolní Moravice v malebném prostředí Jeseníků v areálu Avalanche, 400m od Skiareálu Čerťák.</p>
              <p>V blízkém okolí penzionu je mnoho možností turistického a sportovního vyžití nejen v létě ale i v zimě: lyžování, běžecké trasy, cykloturistika, pěší turistika, geocaching a jiné.
              </p>
              <p>
                V případě zájmu lze domluvit polopenzi.
              </p>
            <p>K ubytování je možnost také objednat stravovací služby firmy Krabky.cz. Přivezeme vám celodenní krabičkovou stravu po dobu ubytování za velmi výhodné ceny. Minimální objednávka je 4 osoby na 2 dny. Pro individuální poptávku nás neváhejte kontaktovat na tel. 725 814 617 nebo <a href="http://www.krabky.cz/">www.krabky.cz.</a></p>
    </div>
</div>
<div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Možnost pronájmu apartmánů:</h2>
            </div>
            <%= link_to room_path(2) do %>
                <div class="col-md-4 text-center">
                    <div class="thumbnail">
                       <img class="img-responsive" src="/pictures/110.JPG" alt="">
                        <div class="caption">
                            <h3>Apartmán 110</h3>
                        </div>
                    </div>
                </div>
            <% end %>
            <%= link_to room_path(1) do %>
                <div class="col-md-4 text-center">
                    <div class="thumbnail">
                        <img class="img-responsive" src="/pictures/109.JPG" alt="">
                        <div class="caption">
                            <h3>Apartmán 109</h3>
                        </div>
                    </div>
                </div>
            <% end %>
            <%= link_to room_path(5) do %>
                <div class="col-md-4 text-center">
                    <div class="thumbnail">
                       <img class="img-responsive" src="/pictures/spodni.JPG" alt="">
                        <div class="caption">
                            <h3>Spodní patro (109 + 110)</h3>
                        </div>
                    </div>
                </div>
            <% end %>
            <%= link_to room_path(3) do %>
                <div class="col-md-4 text-center">
                    <div class="thumbnail">
                        <img class="img-responsive" src="/pictures/111.JPG" alt="">
                        <div class="caption">
                            <h3>Apartmán 111</h3>
                        </div>
                    </div>
                </div>
            <% end %>
            <%= link_to room_path(4) do %>
                <div class="col-md-4 text-center">
                    <div class="thumbnail">
                        <img class="img-responsive" src="/pictures/112.JPG" alt="">
                        <div class="caption">
                            <h3>Apartmán 112</h3>
                        </div>
                    </div>
                </div>
            <% end %>
            <%= link_to room_path(6) do %>
                <div class="col-md-4 text-center">
                    <div class="thumbnail">
                     	<img class="img-responsive" src="/pictures/cely.JPG" alt="">
                        <div class="caption">
                            <h3>Celý penzion</h3>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>

app/views/welcome/pictures.html.erb
<%= render :partial => "welcome/container_header",:locals => {:nazev => 'Fotogalerie'} -%>
<div class="row">
<% @images.each do |image| %>
  <div class="col-md-3 img-portfolio">
      <a href="<%= "#{image.picture.url}" %>"  data-toggle="lightbox"><img class="img-responsive img-hover img-related" src="<%= "#{image.picture.url}" %>"  alt=""></a>
    </div>
<% end %>
</div>

app/views/welcome/price_list.html.erb
<%= render :partial => "welcome/container_header",:locals => {:nazev => 'Ceník'} -%>
<div class="alert alert-info" role="alert">
  <strong>Akční ceny se v kalkulačce nezobrazují!!</strong>
</div>
  <table  class="table table-bordered">
    <thead>
      <tr>
        <th> Typ Apartmánu </th>
        <th> Cena za den při objednávce 1 - 2 dní</th>
        <th> Cena za den při objednávce 3 - 5 dní</th>
        <th> Cena za den při objednávce 6 a více dní</th>
        <th> Cena za den při objednávce 1 - 5 dní do 3 osob</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Apartmán 109</td>
        <td>2000 Kč </td>
        <td>1800 Kč </td>
        <td>1600 Kč </td>
        <td>1700 Kč </td>
      </tr>
      <tr>
        <td>Apartmán 110</td>
        <td>1200 Kč</td>
        <td>1080 Kč</td>
        <td> 960 Kč</td>
        <td></td>
      </tr>
      <tr>
        <td>Apartmán 111</td>
        <td>2400 Kč</td>
        <td>2160 Kč</td>
        <td>1920 Kč</td>
        <td>2040 Kč</td>
      </tr>
      <tr>
        <td>Apartmán 112</td>
        <td>2000 Kč </td>
        <td>1800 Kč </td>
        <td>1600 Kč </td>
        <td>1700 Kč </td>
      </tr>
      <tr>
        <td>Spodní patro</td>
        <td>2800 Kč</td>
        <td>2520 Kč</td>
        <td>2240 Kč</td>
        <td></td>
      </tr>
      <tr>
        <td>Celý penzion</td>
        <td>7200 Kč</td>
        <td>6480 Kč</td>
        <td>5760 Kč</td>
        <td></td>
      </tr>
    </tbody>
  </table>

  <div class="col-sm-6">
  <%= form_for(@order) do |o| %>
    <h4> Kalkulačka pro výpočet </h4>
    <div class="form-group">
      <%= o.label :from_date, 'Od data' %>
      <%= o.text_field :from_date, class: 'datepicker form-control', type: "text" , :required => true %>
    </div>
    <div class="form-group">
      <%= o.label :to_date, 'Do data' %>
      <%= o.text_field :to_date, class: 'datepicker form-control', type: "text" , :required => true %>
    </div>
    <div class="form-group">
      <%= o.label :room_id, 'Typ apartmánu' %>
      <%= o.select :room_id, Room::TYPE_ROOMS,{}, {class: 'form-control'} %>
    </div>
    <div class="form-group">
      <%= o.hidden_field :price , class: 'order_price_new' %>
      <%= o.label :price, 'Výsledná cena' %>
      <input class="form-control" id="price_show" type="text" placeholder="Výsledná cena zde" disabled>
    </div>
    <div class="form-group">
      <p> Při objednávce do 3osob na 1 - 5 dnů sleva 15%. Platí pro apartmány 109, 111, 112, cena se nezobrazuje na kalkulačce pro výpočet. </p>
    </div>
    <div class="form-group">
      <p> V ceně není uveden obecní poplatek. </p>
    </div>
     <div class="form-group">
      <p>Po vytvoření objednávky požadujeme zálohu 50%. </p>
    </div>
	<div class="form-group">
	<p> V době od 26.12.2019 do 4.1.2020 lze pronajmout pouze celý penzion za cenu 55.000,- Kč vč. DPH a místních poplatku.</p>
	</div>
    <% end %>

  </div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker({
        format: 'yyyy/mm/dd',
        startDate: 'd'
    });
  });
</script>