config/routes.rb
Rails.application.routes.draw do
  get 'order/index'

  devise_for :users
  root 'welcome#index'

  resources :welcome do
    collection do
      get 'contact'
      get 'pictures'
      get 'price_list'
      get 'conditions'
      post 'send_mail'
    end
  end

  resources :users
  resources :orders
  resources :rooms
  resources :images

end

app/models/image.rb
class Image < ActiveRecord::Base

    has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

 	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  	belongs_to :room
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def index
		@images= Image.all
	end
	def new
		@image = Image.new
	end


	def create
		@image = Image.new(images_params)
		respond_to do |format|
      		if @image.save
		        flash[:success] = 'Objednávka úspěšně vytvořena.'
		        format.html { redirect_to images_path }
		        format.json { render :show, status: :created, location: @message }
      		else
		        flash[:danger] = 'Obrázek nebyl přidán!!'
		        format.html { render :new }
		        format.json { render json: @message.errors, status: :unprocessable_entity }
      		end
    	end
  	end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_path }
      format.json { head :no_content }
    end
  end

  def show
  end

private
	def images_params
		 params.require(:image).permit(:picture, :room_id)
	end
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/images_helper.rb
module ImagesHelper
  def rooms_name(type_room)
		case type_room
			when Room::ROOMS109
				'Apartmán 109'
  			when Room::ROOMS110
  				'Apartmán 110'
  			when Room::ROOMS111
  				'Apartmán 111'
  			when Room::ROOMS112
  				'Apartmán 112'
  			when Room::ROOMS109110
  				'Spodní patro'
  			when Room::ROOMSall
  				'Celý penzion'
  			else
  				'nedefinovaný'
  		end
	end
end

app/views/images/_form.html.erb
<%= form_for @image, url: images_path, html: { multipart: true } do |i| %>
   <div class="panel-body">
        <div class="form-group control-group">
          <div class="controls">
            <p> Obrázek </p>
            <%= i.file_field :picture ,  :required => true %>
          </div>
        </div>   
        <div class="form-group control-group">
          <div class="controls">
            <p> Apartmán </p>
            <%=  i.select :room_id, Room::TYPE_ROOMS,{}, {class: 'form-control'} %>
          </div>
        </div> 
        
        <div id="success"></div>
        <div class="form-group">
            <%= i.submit 'Přidej obrázek' , class:"btn btn-primary"%>
        </div>   
    </div>
<% end %>

app/views/images/index.html.erb
<%= render :partial => "welcome/container_header",:locals => {:nazev => 'Obrázky'} -%>
<%= link_to "Nový obrázek", new_image_path, id: "new_record", class:"btn btn-primary"%>
<table  class="table">
<thead>
  <tr>
    <th> ID </th>
    <th> Name </th>
    <th> Link na obrázek </th>
    <th> Apartmán </th>
  </tr>
  </thead>
  <tbody>
    <% @images.each do |o|  %>
    <tr>
      <td><%= image_tag o.picture.url, :size => "100x100"  %></td>
    	<td><%= o.picture_file_name %></td>
    	<td><%= link_to "Zobraz obrázek" ,o.picture.url %></td>
      <td><%= rooms_name o.room_id %></td>
       <td><%= link_to 'smazat', o, method: :delete, data: { confirm: 'Jste si jistí?' } if current_user.admin? %></td>
    </tr>
  <% end unless @images.nil? %>
  </tbody>
</table>

app/views/images/new.html.erb
<%= render :partial => "welcome/container_header",:locals => {:nazev => 'Nový obrázek'} -%>
<%= render("form") %>