config/routes.rb
Rails.application.routes.draw do
  get 'order/index'

  devise_for :users
  root 'welcome#index'

  resources :welcome do
    collection do
      get 'contact'
      get 'pictures'
      get 'price_list'
      get 'conditions'
      post 'send_mail'
    end
  end

  resources :users
  resources :orders
  resources :rooms
  resources :images

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Penzion" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Penzion whitezralok', root_path, class:"navbar-brand" %>
      </div>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Fotogalerie',   pictures_welcome_index_path %></li>
              <li><%= link_to 'Ceník',   price_list_welcome_index_path %></li>
              <li><%= link_to 'Kontakty',  contact_welcome_index_path %></li>
              <% if current_user.nil? %>
                <li><%= link_to "Přihlášení", new_user_session_path  %></li>
                <li><%= link_to "Registrace", new_user_registration_path%></li>
              <% else %>
                <li><%= link_to "Objednávky", orders_path(user: current_user)%> </li>
                <li><%= link_to current_user.email, edit_user_path(current_user) %></li>
                 <%if current_user.admin? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" >Admin area
                  <b class="caret"></b> </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Uživatelé", users_path %></li>
                    <li><%= link_to "Obrázky", images_path %></li>
                  </ul>
                </li>
              <% end %>
                <li><%= link_to "Odhlášení",  destroy_user_session_path, method: :delete %> </li>
              <% end %>
              <li><%= link_to "Obchodní podmínky", conditions_welcome_index_path%></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-11">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Whitezralok 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>